trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'

# Restore dependencies
- script: dotnet restore Backend/ProductCatalog.Api/ProductCatalog.Api.csproj
  displayName: 'dotnet restore'

# Build
- script: dotnet build Backend/ProductCatalog.Api/ProductCatalog.Api.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build'

# Publish
- script: dotnet publish Backend/ProductCatalog.Api/ProductCatalog.Api.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish'

# Publish artifact (drop folder)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
